---
  - name: Updating Redis DataBase for {{app}} properties
    #shell: "cat /share/backup/test/artifacts/CM_App_Config_Population/ansible-app-prop-files-list.properties" #test
    shell: "cd {{redis_path}};java -jar vsb-cm.jar -h {{redis_ip}} -p {{redis_port}} -c loadConfig -f ansible-app-prop-files-list.properties -d {{ redis_update }}"
    register: result_redis
  - debug: msg="{{redis_ip}} {{redis_port}} {{redis_update}} {{result_redis.stdout}}"

  - name: Redis Successfully updated for {{app}}
    file: path={{redis_path}}/ansible-app-prop-files-list.properties state=absent
    when: result_redis|succeeded
