---
- hosts: smh
  remote_user: vsb
  vars:
     jar: vsb-smh.jar
     jar_path: "/share/vsb/SMH"
     jar_bk: "/share/backup"
     app: SMH
     app_orig: smh
     app_conf_path: "/share/vsb/SMH/Redis/CM_App_Config_Population"
     app_app: application.properties
     app_cmd: common-data.properties
     app_que: sm-queue-names.properties
     redis_app: "common.app.config=application.properties"
     redis_cmd: "common.data.config=common-data.properties"
     redis_que: "common.queue.names=sm-queue-names.properties"
     redis_path: "/share/vsb/SMH/Redis/CM_App_Config_Population"
     redis_ip: "172.18.14.111"
     redis_port: "8000"
     redis_update: "partial"
#     #lib_home: "/share/backup/test/artifacts/libs" #test
     lib_home: "/share/vsb/artifacts/libs"
     smh_lib_home: "/share/vsb/SMH"     #orig only for smh
     lib_common: "common"
     lib_app: "smh"
     smh_lib_app: "libs"

#     app_stat: "/apps/StartupCSV/c2_status.csv"
     redis_metadat_path: "/share/app-config/cm/CM_Meta_Data_Templates_Population"
     redis_cmn_path: "/share/app-config/cm/CM_App_Config_Population"
     
  tasks:
  - name: Create variable for DD_MM_YYYY
    #command: "date +%d_%m_%Y_%H_%M"
    command: "date +%d_%m_%Y_%H"
    register: date_output

  - name: Create variable {{app}}_IP
    shell: "/sbin/ifconfig|grep -w inet|grep -v 127.0.0|head -n 1|awk '{print $2}'|cut -d ':' -f 2|cut -d '.' -f 4"
    register: ipbk_output
###  - debug: msg="{{ ipbk_output.stdout }}"

  - name: Checking directory for backup
    file:
     path: /share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}
     state: directory
     mode: 0755
     owner: vsb
     group: vsb

#---------------- Jar backup
  - name: Taking backup of {{app}} jar file from Artifacts
    synchronize: src={{jar_path}}/{{jar}} dest={{jar_bk}}/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}
  
  - name: Stopping {{app}} App
    shell: "for i in `ps -eaf  | grep -v grep | grep {{jar}} |awk '{print $2}'`;do echo $i;kill -9 $i;done;"
#    #shell: "ps -eaf  | grep -v grep | grep {{jar}}"
    register: psid_output
    ignore_errors: True
#  - debug: msg="{{psid_output.stdout}}"

#--------------- Common and Metadata
  - debug:
     msg: "*************************************** [ Common and Metadata already UPTODATE ] ***************************************"
    when: commonmetadata != "common-conf"

  - name: Start Common_metada
    include: common_meta.yml
    when: commonmetadata == "common-conf"

  - debug:
     msg: "*************************************** [ Skipping Above steps for Redis Common and Metadata ] ***************************************"
    when: commonmetadata != "common-conf"

#---------------- App libs
#  - name: Unlink Old  Libs for {{lib_app}}
#    file: path={{lib_home}}/{{lib_app}} state=absent

  - name: Link Release Deployment {{lib_app}} App
    file: src=/share/release/{{myrelease}}/{{app_orig}}/libs  dest={{smh_lib_home}}/{{smh_lib_app}} state=link  #only for SMH

#---------------- common libs
#  - name: Unlink Old  Libs for {{lib_common}}
#    file: path={{lib_home}}/{{lib_common}} state=absent

  - name: Link Release Deployment for {{lib_common}}
    file: src=/share/release/{{myrelease}}/{{lib_common}} dest={{lib_home}}/{{lib_common}}  state=link

#---------------- Copying Jar from release
  - name: copying Release Jar files for Deployment {{app}} App
    synchronize: src=/share/release/{{myrelease}}/{{app_orig}}/{{jar}} dest={{jar_path}}

#---------------- Copying Properties files from release
  - name: Updating Properties File {{app}} App
    #synchronize: src=/share/release/{{myrelease}}/{{app_orig}}/config/ dest={{redis_path}}  #orig
    copy: src=/share/release/{{myrelease}}/{{app_orig}}/config/ dest={{redis_path}}    #new orig
    register: update_app_pro

#--e------------ Updating Redis
  - name: Adding App Config and Queue Name in a List for Redis
    #shell: "echo -e '{{redis_conf}}\n{{redis_que}}' > {{redis_path}}/ansible-app-prop-files-list.properties"
    shell: "echo -e {{item}} >> {{redis_path}}/ansible-app-prop-files-list.properties"
    with_items:
        - common.app.config=application.properties
        - common.data.config=common-data.properties
        - common.queue.names=sm-queue-names.properties
    when: update_app_pro|changed

  - name: Now Going for Redis
    include: redis_deploy.yml
    when: update_app_pro|changed

#-- To start App
  - name: Deployment Completed Now Going to Start {{app}} App
    #shell: "hostname"
    shell: "cd {{jar_path}}; nohup /tools/jdk1.7.0_40/bin/java -cp vsb-smh.jar:libs/* com.sprint.vsb.sm.Application /share/vsb/SMH/log4j.properties Default &"

#--- checking App status
  - name: Checking App Status for {{app}}
    #shell: "cat {{app_stat}} |cut -d , -f 3"
    shell: "ps -eaf  | grep -v grep | grep -w vsb-smh.jar|wc -l"
    register: app_stat_output

  - debug:
        msg: "****************************** The {{app}} App Is UP and Running ******************************"
    when: app_stat_output.stdout == "1"

  - debug:
        msg: "****************************** The {{app}} App is NOT Running Properly ******************************"
    when: app_stat_output.stdout != "1"

#  - debug: msg="{{ app_stat_output.stdout }}"

  - lineinfile:
        dest: /share/backup/test/succ
        line: "{{app}} \t| {{inventory_hostname}} \t|== Succeed"
        state: present
        create: True
    when: app_stat_output.stdout == "1"

  - lineinfile:
        dest: /share/backup/test/succ
        line: "{{app}} \t| {{inventory_hostname}} \t|== Failed"
        state: present
        create: True
    when: app_stat_output.stdout != "1"
