---
- name: Engine Start
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
        key_pair: stage_test4
        region: ap-southeast-1

  tasks:
  - name: example3 Key Pair
    ec2_key:
     name: '{{ key_pair }}'
     region: '{{ region }}'
     state: absent
