---
- hosts: facade
  remote_user: vsb
  vars: 
     jar: vsb-facade
     app: FACADE
     app_orig: facade
     app_conf_path: /apps/vsb-facade
     app_app: application.properties

  tasks:

  - name: Create variable for DD_MM_YYYY
    #command: "date +%d_%m_%Y_%H"
    command: "date +%d_%m_%Y_%H_%M"
    register: date_output

  - name: Create variable {{app}}_IP
    shell: "/sbin/ifconfig|grep -w inet|grep -v 127.0.0|head -n 1|awk '{print $2}'|cut -d ':' -f 2|cut -d '.' -f 4"
    register: ipbk_output
#  - debug: msg="{{ ipbk_output.stdout }}"

  - name: Checking directory for backup
    file:
     path: /share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}
     state: directory
     mode: 0755
     owner: vsb
     group: vsb

  - name: archive/backup the files from /apps/vsb-facade
##    shell: "cd /apps/vsb-facade;tar -cvzf /share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}/META-INF.tgz META-INF"
    shell: "cd /apps/;tar -cvzf /share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}/vsb-facade.tgz vsb-facade"
    register: tar_output
  
  - name: Stopping {{app}} App
    shell: "for i in `ps -eaf  | grep -v grep | grep {{jar}} |awk '{print $2}'`;do echo $i;kill -9 $i;done;"
    #shell: "ps -eaf  | grep -v grep | grep {{jar}}"
    register: psid_output
    ignore_errors: True
  - debug: msg="{{psid_output.stdout}}"

  - name: Extarct Jar files for Deployment {{app}} App
    #shell: "unzip -o /share/release/{{myrelease}}/vsb-facade/vsb-facade*.jar -d /share/backup/vsb-facade"
    shell: "unzip -o /share/release/{{myrelease}}/vsb-facade/vsb-facade*.jar -d {{app_conf_path}}"

  - name: Coppying Applcation properties file {{app}} App
    copy: src=/share/release/{{myrelease}}/vsb-facade/{{app_app}} dest={{app_conf_path}}
    #copy: src=/share/release/{{myrelease}}/vsb-facade/{{app_app}} dest=/share/backup/vsb-facade

## TO remove dev file
  - name: Successfully Copied for {{app}}
    file: path=/apps/vsb-facade/application-dev.properties state=absent
    ignore_errors: True

  - name: Deployment Completed Now Going to Start {{app}} App
    #shell: "hostname"
    shell: "cd /apps/; nohup java -cp vsb-facade org.springframework.boot.loader.JarLauncher &"
