---
- hosts: smh
  remote_user: vsb
  vars: 
     jar: vsb-smh.jar
     jar_path: "/share/vsb/SMH"
     app: SMH
     app_orig: smh
     app_conf_path: "/share/vsb/SMH/Redis/CM_App_Config_Population"
     app_app: application.properties
     app_cmd: common-data.properties
     app_que: sm-queue-names.properties
     redis_app: "common.app.config=application.properties"
     redis_cmd: "common.data.config=common-data.properties"
     redis_que: "common.queue.names=sm-queue-names.properties"
     redis_path: "/share/vsb/SMH/Redis/CM_App_Config_Population"
     redis_ip: "172.18.14.111"
     redis_port: "8000"
     redis_update: "partial"
     

  tasks:
  - name: Create variable for DD_MM_YYYY
    #command: "date +%d_%m_%Y_%H"
    command: "date +%d_%m_%Y_%H_%M"
    register: date_output

  - name: Create variable {{app}}_IP
    shell: "/sbin/ifconfig|grep -w inet|grep -v 127.0.0|head -n 1|awk '{print $2}'|cut -d ':' -f 2|cut -d '.' -f 4"
    register: ipbk_output

  - name: Checking directory for backup
    file:
     path: /share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}/config
     state: directory
     mode: 0755
     owner: vsb
     group: vsb

  - name: Taking backup of {{app}} jar file from Artifacts
    copy: src={{jar_path}}/{{jar}} dest=/share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}
  
  - name: Stopping {{app}} App
    shell: "for i in `ps -eaf  | grep -v grep | grep {{jar}} |awk '{print $2}'`;do echo $i;kill -9 $i;done;"
    #shell: "ps -eaf  | grep -v grep | grep {{jar}}"
    register: psid_output
    ignore_errors: True
  - debug: msg="{{psid_output.stdout}}"

  - name: Taking backup of App file for {{app}}
    copy: src={{app_conf_path}}/{{app_app}} dest=/share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}/config

  - name: Taking backup of Common Data file for {{app}}
    copy: src={{app_conf_path}}/{{app_cmd}} dest=/share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}/config

  - name: Taking backup of Queue file for {{app}}
    copy: src={{app_conf_path}}/{{app_que}} dest=/share/backup/{{app_orig}}_{{ipbk_output.stdout}}/{{date_output.stdout}}/config

  - name: Coppying Release  App file
    copy: src=/share/release/{{myrelease}}/config/{{app_app}} dest={{app_conf_path}}
    #copy: src=/share/release/{{myrelease}}/config/{{app_app}} dest=/share/backup/
    register: result_app
    ignore_errors: True

  - name: Coppying Release Common Data file
    copy: src=/share/release/{{myrelease}}/config/{{app_cmd}} dest={{app_conf_path}}
    #copy: src=/share/release/{{myrelease}}/config/{{app_cmd}} dest=/share/backup/
    register: result_cmd
    ignore_errors: True

  - name: Coppying Release Queue file
    copy: src=/share/release/{{myrelease}}/config/{{app_que}} dest={{app_conf_path}}
    #copy: src=/share/release/{{myrelease}}/config/{{app_que}} dest=/share/backup/
    register: result_queue
    ignore_errors: True

  - name: Addin Common App Name in a List for Redis
    shell: "echo {{redis_app}} > {{redis_path}}/ansible-app-prop-files-list.properties"
    #shell: "echo {{redis_app}} > /share/backup/ansible-app-prop-files-list.properties"
    when: result_app|succeeded

  - name: Addin Queue Name in a List for Redis
    shell: "echo {{redis_cmd}} >> {{redis_path}}/ansible-app-prop-files-list.properties"
    #shell: "echo {{redis_cmd}} >> /share/backup/ansible-app-prop-files-list.properties"
    when: result_cmd|succeeded

  - name: Addin Queue Name in a List for Redis
    shell: "echo {{redis_que}} >> {{redis_path}}/ansible-app-prop-files-list.properties"
    #shell: "echo {{redis_que}} >> /share/backup/ansible-app-prop-files-list.properties"
    when: result_queue|succeeded

  - name: Now Going for Redis
    include: redis_deploy.yml
    when: (result_app|succeeded) or (result_cmd|succeeded) or (result_queue|succeeded)
 
  - name: Coppying Release Jar file for Deployment {{app}} App
    copy: src=/share/release/{{myrelease}}/{{jar}} dest={{jar_path}}
    #copy: src=/share/release/{{myrelease}}/{{jar}} dest=/share/backup/
    ignore_errors: True


  - name: Deployment Completed Now Going to Start {{app}} App
    #shell: "hostname"
    shell: "cd {{jar_path}}; nohup /tools/jdk1.7.0_40/bin/java -cp vsb-smh.jar:libs/* com.sprint.vsb.sm.Application /share/vsb/SMH/log4j.properties Default &"
