
---
- hosts: c2
  remote_user: vsb
  vars: 
     jar: vsb-c2.jar
     jar_path: "/share/backup/test/artifacts"
     #jar_path: "/share/vsb/artifacts"
     jar_bk: "/share/backup/test"
     #jar_bk: "/share/backup"
     app: C2
     app_orig: c2
     app_conf_path: "/share/app-config/cm/CM_App_Config_Population"
     app_conf: c2-app-config.properties
     app_que: c2-queue-names.properties
     redis_conf: "c2.app.config=c2-app-config.properties"
     redis_que: "c2.queue.names=c2-queue-names.properties"
     redis_path: "/share/backup/test/artifacts/CM_App_Config_Population"
     #redis_path: "/share/app-config/cm/CM_App_Config_Population"
     redis_ip: "172.18.14.111"
     redis_port: "8000"
     redis_update: "partial"
     lib_home: "/share/backup/test/artifacts/libs"
#     #lib_home: "/share/vsb/artifacts/libs"
     lib_common: "common"
     lib_app: "c2"
     #app_stat: "/apps/StartupCSV/c2_status.csv"
     app_stat: "/share/backup/test/artifacts/c2_status.csv"
     

  tasks:
  - name: Checking App Status for {{app}}
    shell: "cat {{app_stat}} |cut -d , -f 3"
    register: app_stat_output
  - debug: msg="{{ app_stat_output.stdout }}"

  - name: The {{app}} App Is UP and Running
    shell: "cat {{app_stat}}"
    when: app_stat_output.stdout == "1"


  - name: The {{app}} App is Not Running Properly
    shell: "cat {{app_stat}}"
    when: app_stat_output.stdout == "-1"
